### ISSUE TITLE
How to extract auto-generated and auto-translate closed captions?

### ISSUE THREAD

**Issue by tuanbs** [Hexer10/youtube_explode_dart#50]
First of all, thanks for this awesome plugin. Just wondering if we can extract the `auto-generated` and `auto-translate` closed captions?

I can extract `human-generated` closed captions, but when I tried the `auto-generated` and `auto-translate`  ones, I got the null result. If not supported yet, hope it is possible in the next version. And please keep evolving this plugin. You guys are doing awesome job. Cheers.

**Comment by Hexer10** [comment]
Fetching auto-translated closed captions is not yet support, I'm planning to implement it in the coming days

**Comment by Hexer10** [comment]
This was implemented see the unit tests to have an idea on how to implement this: https://github.com/Hexer10/youtube_explode_dart/blob/a9275af1e20d1c784e99f9afdc0c26701f81c539/test/closed_caption_test.dart#L14-L52

**Comment by tuanbs** [comment]
Hello, thanks for this. The `auto-generated` works fine, but the `auto-translate` is not working. Hope it's supported in the near future.

**Comment by Hexer10** [comment]
Seems like youtube implement some changes recently now the request must include some kind of specific query parameter, I'll look into this when I have time

**Comment by Hexer10** [comment]
It now should be fixed please read the changelog and try again

**Comment by tuanbs** [comment]
Hello, thanks for the update. But it's still not working with `auto-translate` track. For ex, I tried the following test and got the `null` result:
```dart
var manifest = await yt.videos.closedCaptions.getManifest('WOxr2dmLHLo');
var trackInfo = manifest.tracks.firstWhere((element) => element.language.code == 'vi', orElse: () => null);
if (trackInfo != null) {
    var subtitles = await yt.videos.closedCaptions.getSubTitles(trackInfo);
}
```
I got `null` value for `trackInfo`. But as you can see in the attached image, the video has Vietnamese (`vi`) auto-translate track:
<img width="293" alt="Screen Shot 2020-12-31 at 10 57 21 am" src="https://user-images.githubusercontent.com/4801395/103387427-d607b780-4b57-11eb-8ca6-8a8036b206b6.png">

**Comment by Hexer10** [comment]
Youtube does not provide autotranslated tracks by default you first need to get a track provided by youtube, and then autotranslate it:
```
var manifest = await yt.videos.closedCaptions.getManifest('WOxr2dmLHLo');
var trackInfo = manifest.getByLanguage('en', autoGenerate: false, format: ClosedCaptionFormat.srv3); // Or manifest.tracks.first if you just want to get an available track.
if (trackInfo != null) {
    var subtitles = await yt.videos.closedCaptions.getSubTitles(trackInfo);
}
``

**Comment by tuanbs** [comment]
@Hexer10 Does that mean `youtube_explode_dart` cannot extract the auto-translate track? I think it should be possible because I see `Youtube-dl` can extract it.

**Comment by Hexer10** [comment]
You can extract them it's just that you can't directly.
To explain it clearly: Youtube only provides some subtitles tracks by default (those uploaded by the user and autogenerated ones, iirc they are in the language of the video), the translation of the tracks is not available right away and you need to generate their url with the code I posted before:
```dart
var manifest = await yt.videos.closedCaptions.getManifest('WOxr2dmLHLo');
var trackInfo = manifest.getByLanguage('en', autoGenerate: false, format: ClosedCaptionFormat.srv3); // Or manifest.tracks.first if you just want to get an available track.
if (trackInfo != null) {
    var subtitles = await yt.videos.closedCaptions.getSubTitles(trackInfo.autoTranslate('it'));
}
```

PS: I'm only now noticing that I posted the wrong code in the previous comment, sorry

**Comment by tuanbs** [comment]
@Hexer10 Awesome. Finally I'm able to get the auto-translate CC thanks to your code. Thank you very much. Please keep evolving this plugin as you guys are doing amazing job. 🥇
